language: go
go_import_path: github.com/aws/amazon-ecs-agent
sudo: false
go:
  - 1.12

matrix:
  include:
    - os: windows
      script:
        - go test -v -race -tags unit -run "^Test.*InactivityTimeout$" -count 1000 -timeout 100m ./agent/dockerclient/dockerapi/
